name = "STARFORGED 4"
author = "STARPLANET"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f510998723d3b407117a7f9416296b94929c77cda105293ba1be72c364c208f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
